### ISSUE TITLE
KeyError with SSH connections

### ISSUE THREAD

**Issue by alexrudd2** [FrameOS/frameos#15]
```
File "/home/alex/git/frameos/backend/app/utils/ssh_utils.py", line 34, in remove_ssh_connection
17:24:49 huey.1  |     ssh_connections.remove(ssh)
17:24:49 huey.1  | KeyError: None
```

I'm pretty sure this is an under-indented line in `restart_frame.py`.
https://github.com/FrameOS/frameos/blob/c1e30c28b88c74318fee31ac28a095e5460502e7/backend/app/tasks/restart_frame.py#L32-L40

`remove_ssh_connection(ssh)` should be in the `finally:` block like in `reset_frame.py`
https://github.com/FrameOS/frameos/blob/c1e30c28b88c74318fee31ac28a095e5460502e7/backend/app/tasks/deploy_frame.py#L134-L142

**Comment by mariusandra** [comment]
Thanks! Seems to have been the issue.
