### ISSUE TITLE
Clock overlay time not update

### ISSUE THREAD

**Issue by ngothanhnghi** [FrameOS/frameos#36]
I followed the demo instruction and add the clock overlay as follow:

Event rendering --> Vanilla boilerplate "Code" --> Clock overlay

Actual behavior
The vanilla log message was printed with a period, however, the clock time rendered in the e-ink panel isn't updated. 

Expected behavior:
Time is updated every now and then when rendering event happens.

**Comment by mariusandra** [comment]
Hey @ngothanhnghi , can you share some screenshots to help me reproduce the situation? From the above I'm sadly not able to provide much help.

What have you tried? Does it work if you change the order of the apps?

**Comment by ngothanhnghi** [comment]
This is the setup
![Uploading Screenshot 2024-01-08 at 5.39.39 PM.png…]()

Log 
[Uploading overlay_clock.log…]()

**Comment by ngothanhnghi** [comment]
The code part is added to print out the log line "Hello from render "

**Comment by mariusandra** [comment]
Under "Frame Settings", what do you have as the refresh interval?

<img width="417" alt="image" src="https://github.com/FrameOS/frameos/assets/53387/352c0049-7073-4008-a07c-0fd23fe63bb9">

**Comment by ngothanhnghi** [comment]
thank you that fixes the problem, not aware of this setting. should mention it in the guide/demo as this is an important feature
